#!/bin/sh

case "$1" in
    start)
        echo "Loading kernel modules"
        ;;
    stop)
        echo "Unloading kernel modules"
        ;;
    *)
        echo "Usage: $0 {start|stop}"

    exit 1
esac

exit 0